/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118457-gd6a364e7c3-20250210"
#endif /* AVUTIL_FFVERSION_H */
